### PR TITLE
2.1 Portuguese translation

### PR DESCRIPTION
**Pull request by JAlexandre**
Arnaud,

Here is the Portuguese translation revised for 2.1

Cheers,

Joao

### CODE REVIEW

**Comment by ArnaudD** [comment]
I merged the translation, but it will need some rework since I messed with punctuation in translation strings.

**Comment by JAlexandre** [comment]
Hi Arnaud,

Sorry, what exactly do you need from me? Redo the translation?

**Comment by ArnaudD** [comment]
I've made some mistakes in the source by removing punctuation. I will add them again and I will need you to check if there is something to change on the translation you gave me. Sorry for the double work.

I will keep you updated once I've made the corrections. Hopefully we should have an online localisation service to make it easier for contributor, I'm actually trying several one. ex: http://www.getlocalization.com/FileZ/

**Comment by JAlexandre** [comment]
OK, I wait for you and  I'll review the translation ASAP.
The localization service looks nice.

**Comment by JAlexandre** [comment]
Hi Arnaud,

Do you still need my assistance to revise the Portuguese translation?

If you do, please alert me when ever we're good to go.

Regards,

Joao

**Pull request closed without merging**
